version: '3.2'

services:
  syncrolized_univ_app:
    image: registry.russu.xyz:443/syncrolized_univ_app:1.0.1
    build:
      context: .
    container_name: syncrolized_univ
    restart: always
    ports:
      - 8001:5000
    command: python3 -m infrastructure
